# Generated by Django 4.2 on 2024-12-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_anouncement_available_courses_coursemodule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
