# Generated by Django 4.2 on 2024-12-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_category_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
