# Generated by Django 4.2 on 2024-11-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0038_paystackpayment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sturegistercourse',
            new_name='studentregistercourse',
        ),
    ]
