# Generated by Django 4.2 on 2024-11-26 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0039_rename_sturegistercourse_studentregistercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentregistercourse',
        ),
    ]
