# Generated by Django 4.2 on 2024-11-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0041_registercoursestu'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystackpayment',
            name='user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paystackpayment',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
