# Generated by Django 4.2 on 2024-11-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0043_transaction_delete_paystackpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, null=True, verbose_name='Student Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_tutor',
            field=models.BooleanField(default=False, null=True, verbose_name='Tutor Status'),
        ),
    ]
