# Generated by Django 4.2 on 2024-11-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0044_alter_user_is_student_alter_user_is_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_affiliate',
            field=models.BooleanField(default=False, null=True, verbose_name='Affiliate Status'),
        ),
    ]
