# Generated by Django 4.2 on 2024-11-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0046_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_affiliate',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Affiliate Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Student Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_tutor',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tutor Status'),
        ),
    ]
