# Generated by Django 4.2 on 2024-11-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0048_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
