# Generated by Django 4.2 on 2024-11-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0050_alter_user_date_joined_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
