# Generated by Django 4.2 on 2024-11-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0051_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Active Status'),
        ),
    ]
