# Generated by Django 4.2 on 2024-11-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0052_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
