# Generated by Django 4.2 on 2024-11-29 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0053_alter_user_options_coursemodule_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moduleliveclass', to='Users.coursemodule'),
        ),
    ]
