# Generated by Django 4.2 on 2024-11-29 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0055_referal'),
    ]

    operations = [
        migrations.CreateModel(
            name='promotedcourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coursepromotedcourse', to='Users.available_courses')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userpromotedcourse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
