# Generated by Django 4.2 on 2024-11-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0056_promotedcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotedcourses',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
