# Generated by Django 4.2 on 2024-11-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0057_promotedcourses_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotedcourses',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='promotedcourses',
            name='title',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
