# Generated by Django 4.2 on 2024-12-01 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0060_referraltracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='referal',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to='Users.referal'),
        ),
    ]
