# Generated by Django 4.2 on 2024-12-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0061_referal_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
