# Generated by Django 4.2 on 2024-12-01 11:18

import Users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0062_user_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referraltracker',
            name='referred_user',
        ),
        migrations.RemoveField(
            model_name='referraltracker',
            name='referrer',
        ),
        migrations.AddField(
            model_name='user',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=Users.models.generate_referral_code, max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Referal',
        ),
        migrations.DeleteModel(
            name='ReferralTracker',
        ),
    ]
