# Generated by Django 4.2 on 2024-12-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0063_remove_referraltracker_referred_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referal_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
