# Generated by Django 4.2 on 2024-12-01 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0065_alter_user_referrer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referal_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referrer',
        ),
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referal_code', models.CharField(max_length=255, null=True, unique=True)),
                ('referal_link', models.CharField(max_length=255, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to='Users.referal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userreferal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
