# Generated by Django 4.2 on 2024-12-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0067_user_referral_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='referral_link',
            new_name='referer',
        ),
    ]
